language: node_js
node_js:
  - "7"
branches:
  only:
    - master
#before_install:
before_script:
  - git config --global user.email "test@test.com"
  - git config --global user.name "Testing Tester"
  - npm install
script:
  - node publish-to-local-docs.js
after_success:
  - npm version minor
  - git add .
  - git commit -m "New minor version"
  - git push
#deploy:
#  - npm publish
notifications:
  email:
    recipients:
      - andrew@harmel-law.com
    on_success: [change]
    on_failure: [always]
