language: node_js
node_js:
  - "7"
branches:
  only:
    - master
before_script:
  - npm install
script:
  - npm version minor --no-git-tag-version
  - node publish-to-local-docs.js
after_success:
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis CI"
  - git remote rm origin
  - git remote add origin https://andrewharmellaw:$GITHUB_API_KEY@github.com/andrewharmellaw/quest-dist-sys-eng-java-apprentice.git
  - git remote -v
  - git fetch
  - git checkout master
  - git add .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed version %s [skip ci]"
  - git push origin master
notifications:
  email:
    recipients:
      - andrew@harmel-law.com
    on_success: [change]
    on_failure: [always]
