language: node_js
node_js:
  - "7"
branches:
  only:
    - master
#before_install:
before_script:
  - npm install
script:
  - node publish-to-local-docs.js
after_success:
  - npm version minor
  - ./release-site.sh
#deploy:
#  - npm publish
notifications:
  email:
    recipients:
      - andrew@harmel-law.com
    on_success: [change]
    on_failure: [always]
