language: node_js
node_js:
  - "7"
branches:
  only:
    - master
before_script:
  - npm install
script:
  - node publish-to-local-docs.js
  - generate-release --release-type minor
notifications:
  email:
    recipients:
      - andrew@harmel-law.com
    on_success: [change]
    on_failure: [always]

