language: node_js
node_js:
  - "7"
branches:
  only:
    - master
#before_install:
before_script:
  - npm install
script:
  - node publish-to-local-docs.js
after_success:
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis CI"
  - git remote rm origin
  - git remote add origin https://andrewharmellaw:$GITHUB_API_KEY@github.com/andrewharmellaw/quest-dist-sys-eng-java-apprentice.git
  - git remote -v
  - git fetch
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH
  - git add .
  - git commit -m "Updated site."
  - npm version minor -m "Travis build $TRAVIS_BUILD_NUMBER pushed version %s [skip ci]"
  - git push origin $TRAVIS_PULL_REQUEST_BRANCH
#deploy:
#  - npm publish
notifications:
  email:
    recipients:
      - andrew@harmel-law.com
    on_success: [change]
    on_failure: [always]
