language: node_js
node_js:
  - "7"
branches:
  only:
    - master
#before_install:
before_script:
  - npm install
script:
  - node publish-to-local-docs.js
after_success:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis CI"
  - git status
  - git remote -v
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH
  - git add .
  - git commit -m "Updated site."
  - git status
  - npm version minor
  - git status
#  - git remote rm origin
#  - git remote add origin https://andrewharmellaw:$GITHUB_API_KEY@github.com/andrewharmellaw/quest-dist-sys-eng-java-apprentice.git
#  - git add .
#  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed [skip ci]"
#  - git status
#  - git push -fq origin master > /dev/null
#  - git status
#deploy:
#  - npm publish
notifications:
  email:
    recipients:
      - andrew@harmel-law.com
    on_success: [change]
    on_failure: [always]
